// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfVlGgSyvLvsTaTjnLlS6gmRegiHJ1oeA',
    appId: '1:307738953807:web:5add62c49e96c22b51023a',
    messagingSenderId: '307738953807',
    projectId: 'aura-watch1',
    authDomain: 'aura-watch1.firebaseapp.com',
    storageBucket: 'aura-watch1.firebasestorage.app',
    measurementId: 'G-ZPD6YJQR37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxN62koIbxrW6yRDQdkHvVZXPzMXwv5Y',
    appId: '1:307738953807:android:9e77d8f6269a6e0151023a',
    messagingSenderId: '307738953807',
    projectId: 'aura-watch1',
    storageBucket: 'aura-watch1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbntNOpiaJtXNyZ2qwe-BQYF4NJBMmUL4',
    appId: '1:307738953807:ios:3729a16cd9879cef51023a',
    messagingSenderId: '307738953807',
    projectId: 'aura-watch1',
    storageBucket: 'aura-watch1.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbntNOpiaJtXNyZ2qwe-BQYF4NJBMmUL4',
    appId: '1:307738953807:ios:3729a16cd9879cef51023a',
    messagingSenderId: '307738953807',
    projectId: 'aura-watch1',
    storageBucket: 'aura-watch1.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfVlGgSyvLvsTaTjnLlS6gmRegiHJ1oeA',
    appId: '1:307738953807:web:68c51ec89a19370d51023a',
    messagingSenderId: '307738953807',
    projectId: 'aura-watch1',
    authDomain: 'aura-watch1.firebaseapp.com',
    storageBucket: 'aura-watch1.firebasestorage.app',
    measurementId: 'G-565MLS9KF8',
  );

}